<?php

/**
 * @file
 * Contains bar_exchange.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bar_exchange_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bar_exchange module.
    case 'help.page.bar_exchange':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bar exchange party!') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_data().
 */
function bar_exchange_views_data() {
  /*$data['bar_exchange_price_log'] = [
    'table' => [
      'group' => 'Bar Exchange',
      'provider' => 'bar_exchange',
      'base' => [
        'field' => 'id',
        'title' => 'Bar exchange price logs',
      ],
    ],
    'id' => [],
  ];*/
}